CHANGELOG.md, Jenkinsfile, package.json, translations/ui-plugin-find-organization/en_US.json
Initial release
https://issues.folio.org/browse/UIORGS-40
While it's helpful for …
=> Release v1.0.0

translations/ui-plugin-find-organization/en_US.json
=> Update translation strings as of 20190429T154045

package.json, translations/ui-plugin-find-organization/en.json
https://issues.folio.org/browse/UIORGS-62
fix translation
While it's helpful for …
=> UIORGS-62 Update Vendor plugin modal's second column title

translations/ui-plugin-find-organization/ar.json, translations/ui-plugin-find-organization/ca.json, translations/ui-plugin-find-organization/da.json, translations/ui-plugin-find-organization/de.json, translations/ui-plugin-find-organization/en_GB.json, translations/ui-plugin-find-organization/en_SE.json, translations/ui-plugin-find-organization/en_US.json, translations/ui-plugin-find-organization/es.json, translations/ui-plugin-find-organization/es_419.json, translations/ui-plugin-find-organization/es_ES.json, translations/ui-plugin-find-organization/fr.json, translations/ui-plugin-find-organization/fr_FR.json, translations/ui-plugin-find-organization/hu.json, translations/ui-plugin-find-organization/it_IT.json, translations/ui-plugin-find-organization/pt_BR.json, translations/ui-plugin-find-organization/pt_PT.json, translations/ui-plugin-find-organization/zh_CN.json
=> Update translation strings as of 20190507T141001

translations/ui-plugin-find-organization/en_US.json
=> Update translation strings as of 20190510T130015

OrganizationSearch/OrganizationSearch.js
=> pass id as prop to organization search, refs ERM-220

.editorconfig, .eslintrc, CHANGELOG.md, OrganizationSearch/OrganizationSearch.js, OrganizationSearch/OrganizationSearchModal.js, package.json
Release of v1.2.0
https://issues.folio.org/browse/UIORGS-77
While it's helpful for …
=> Release v1.2.0

OrganizationSearch/OrganizationSearch.js
=> add buttonProps prop to OrganizationSearch, refs ERM-230

translations/ui-plugin-find-organization/zh_CN.json
=> Update translation strings as of 20190729T163855

OrganizationSearch/OrganizationSearch.css, OrganizationSearch/OrganizationSearchModal.js
https://issues.folio.org/browse/UIOR-305
modal styles
While it's helpful for reviewers …
=> UIOR-305 Scrolling bug in the PO Vendor lookup

translations/ui-plugin-find-organization/ar.json
=> Update translation strings as of 20190807T131714

translations/ui-plugin-find-organization/ar.json
=> Update translation strings as of 20190828T124751

translations/ui-plugin-find-organization/it_IT.json
=> Update translation strings as of 20190925T125755

translations/ui-plugin-find-organization/ru.json, translations/ui-plugin-find-organization/zh_TW.json
=> Update translation strings as of 20191014T135140

translations/ui-plugin-find-organization/ja.json
=> Update translation strings as of 20191028T205642

translations/ui-plugin-find-organization/en.json
Update plugin header from Vendors to Organizations
https://issues.folio.org/browse/UIPFO-3 …
=> UIPFI-3 Update plugin header

translations/ui-plugin-find-organization/ca.json, translations/ui-plugin-find-organization/da.json, translations/ui-plugin-find-organization/de.json, translations/ui-plugin-find-organization/en_GB.json, translations/ui-plugin-find-organization/en_SE.json, translations/ui-plugin-find-organization/en_US.json, translations/ui-plugin-find-organization/es.json, translations/ui-plugin-find-organization/es_419.json, translations/ui-plugin-find-organization/es_ES.json, translations/ui-plugin-find-organization/fr.json, translations/ui-plugin-find-organization/fr_FR.json, translations/ui-plugin-find-organization/hu.json, translations/ui-plugin-find-organization/ja.json, translations/ui-plugin-find-organization/pt_PT.json, translations/ui-plugin-find-organization/ru.json
=> Update translation strings as of 20191106T134035

translations/ui-plugin-find-organization/pt_BR.json, translations/ui-plugin-find-organization/ru.json
=> Update translation strings as of 20191111T233434

translations/ui-plugin-find-organization/he.json
=> Update translation strings as of 20191114T012425

translations/ui-plugin-find-organization/fr_FR.json
=> Update translation strings as of 20191119T231120

translations/ui-plugin-find-organization/fr_FR.json
=> Update translation strings as of 20191122T140350

translations/ui-plugin-find-organization/ru.json
=> Update translation strings as of 20191202T021928

translations/ui-plugin-find-organization/zh_CN.json
=> Update translation strings as of 20191203T022312

CHANGELOG.md, PULL_REQUEST_TEMPLATE.md, package.json
Create `ui-plugin-find-organization` release
https://issues.folio.org/browse/UIPFO-5 …
=> Release v1.5.0

translations/ui-plugin-find-organization/es_ES.json
=> Update translation strings as of 20191216T170438

translations/ui-plugin-find-organization/en_SE.json, translations/ui-plugin-find-organization/es.json, translations/ui-plugin-find-organization/es_419.json
=> Update translation strings as of 20191220T210632

package.json
https://issues.folio.org/browse/UIPFO-7 …
=> UIPFO-7 upgrade eslint

translations/ui-plugin-find-organization/ur.json
=> Update translation strings as of 20200210T220102

package.json
=> bump stripes v3

CHANGELOG.md, OrganizationSearch/OrganizationsListSearchConfig.js, package.json
https://issues.folio.org/browse/UIPFO-9 …
=> Release v2.0.0

translations/ui-plugin-find-organization/ja.json
=> Update translation strings as of 20200413T183215

translations/ui-plugin-find-organization/zh_TW.json
=> Update translation strings as of 20200424T193712

CHANGELOG.md, OrganizationSearch/OrganizationsList.js, OrganizationSearch/OrganizationsListContainer.js, OrganizationSearch/constants.js
Organizations is not using the same Expand/Collapse as implemented in Q4 2019
https://issues.folio.org/browse/UIORGS-151
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> UIORGS-151 Use common buttons for expand/collapse filters pane

translations/ui-plugin-find-organization/zh_TW.json
=> Update translation strings as of 20200505T210535

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIPFO-10 …
=> UIPFO-10 Update to Stripes v4

CHANGELOG.md, OrganizationSearch/OrganizationsListContainer.js, package.json
https://issues.folio.org/browse/UIORGS-178 …
=> UIORGS-178 Switch to mod-organizations

translations/ui-plugin-find-organization/en_GB.json, translations/ui-plugin-find-organization/en_SE.json, translations/ui-plugin-find-organization/en_US.json
=> Update translation strings as of 20200527T144757

package.json
=> Uisacqcomp 3 stripes deps

CHANGELOG.md, package.json
=> Upgrade stripes v5

package.json
fix translation missing warnings  …
=> add-stripes-dep-organizations

package.json
Reverts folio-org/ui-plugin-find-organization#57
=> Revert "add-stripes-dep-organizations"

OrganizationSearch/OrganizationsList.js
=> fix glitch

translations/ui-plugin-find-organization/ar.json, translations/ui-plugin-find-organization/hi_IN.json, translations/ui-plugin-find-organization/ko.json
=> Update translation strings as of 20200921T192032

OrganizationSearch/OrganizationSearch.js
=> add disabled prop

translations/ui-plugin-find-organization/pl.json
=> Update translation strings as of 20200924T211627

translations/ui-plugin-find-organization/de.json
=> Update translation strings as of 20201005T202004

translations/ui-plugin-find-organization/ber.json
=> Update translation strings as of 20201109T135508

CHANGELOG.md, PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/UIPFO-16 …
=> UIPFO-16 Add personal data disclosure form

.eslintrc, OrganizationSearch/OrganizationsListContainer.js
fix filtering of array fields, corresponding PR in SAC https://github.com/folio-org/stripes-acq-components/pull/414
initial PR introduced https://github.com/folio-org/stripes-acq-components/pull/394
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> fix filtering array fields

package.json
=> revert bumping react

.gitignore, CHANGELOG.md, Jenkinsfile, OrganizationSearch/OrganizationSearch.js, OrganizationSearch/OrganizationSearch.test.js, OrganizationSearch/OrganizationSearchModal.test.js, OrganizationSearch/OrganizationsList.test.js, OrganizationSearch/OrganizationsListContainer.test.js, OrganizationSearch/OrganizationsListFilter.js, OrganizationSearch/OrganizationsListFilter.test.js, jest.config.js, package.json
https://issues.folio.org/browse/FAT-42 …
=> FAT-42 UI tests replacement with RTL/Jest

OrganizationSearch/OrganizationSearch.test.js, OrganizationSearch/OrganizationSearchModal.test.js, OrganizationSearch/OrganizationsList.test.js, OrganizationSearch/OrganizationsListContainer.test.js
=> FAT-42 Tests

jest.config.js
=> FOLIO-3050 update coverage report path

CHANGELOG.md, Jenkinsfile, OrganizationSearch/OrganizationSearch.js, OrganizationSearch/OrganizationSearch.test.js, jest.config.js, package.json
https://issues.folio.org/browse/UIPFO-20 …
=> UIPFO-20 Compile Translation Files into AST

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIPFO-21 …
=> UIPFO-21 increment stripes to v7

CHANGELOG.md, OrganizationSearch/OrganizationsList.js, OrganizationSearch/OrganizationsList.test.js
https://issues.folio.org/browse/UIPFO-27 …
=> UIPFO-27 Select filter should announce the number of Results in the Results List pane header

CHANGELOG.md, OrganizationSearch/FindOrganization.test.js
https://issues.folio.org/browse/UIPFO-35
https://github.com/folio-org/ui-plugin-find-organization/pull/104#pullrequestreview-1148914462
Use constant value for limit in failed tests.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> UIPFO-35 Update unit tests before release

.github/workflows/build-npm-release.yml
There is no `./src` dir in plugin directory
While it's helpful for reviewers to help …
=> Update SQ_ROOT_DIR env var

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIPFO-36 …
=> UIPFO-36 bump stripes to 8.0.0 for Orchid/2023-R1

OrganizationSearch/hooks/useOrganizations/useOrganizations.js, package.json
https://issues.folio.org/browse/UIPFO-37?focusedCommentId=173375&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-173375
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> UIPFO-37 Normalize search params to pass to query builder

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json
https://issues.folio.org/browse/UIPFO-41 …
=> UIPFO-41 Upgrade `Node` to `18` version in GitHub Actions

CHANGELOG.md, OrganizationSearch/OrganizationsListFilter/OrganizationsListFilter.js, OrganizationSearch/OrganizationsListFilter/OrganizationsListFilter.test.js, OrganizationSearch/constants.js, package.json
[UIPFO-44](https://issues.folio.org/browse/UIPFO-44)
https://github.com/folio-org/ui-plugin-find-organization/assets/116072773/32b63294-51b8-41f3-85aa-bb5421a784ee
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> UIPFO-44: Add the "Is Donor" filter selectable options for filters pane

OrganizationSearch/OrganizationsListFilter/OrganizationsListFilter.js, OrganizationSearch/OrganizationsListFilter/OrganizationsListFilter.test.js
=> UIPFO-46: fix missing label id

CHANGELOG.md, OrganizationSearch/FindOrganization.js, OrganizationSearch/OrganizationsSearchConfig.js, OrganizationSearch/OrganizationsSearchConfig.test.js, OrganizationSearch/hooks/useOrganizations/useOrganizations.js, OrganizationSearch/hooks/useOrganizations/useOrganizations.test.js
https://issues.folio.org/browse/UIPFO-47
Certain libraries need to store organization-specific banking and account information in the organization record, independent of the normal account information stored in an organization record. This banking information is sensitive and requires its own permissions in order to view. These permissions may be assigned to external systems via API in some instances.
https://github.com/folio-org/ui-plugin-find-organization/assets/88109087/702d72d6-667e-40b2-bef4-8c189c6596b8
- What other …
=> UIPFO-47 Search organization on bank account number

CHANGELOG.md, OrganizationSearch/OrganizationsListFilter/OrganizationsListFilter.js, OrganizationSearch/OrganizationsSearchConfig.js, OrganizationSearch/constants.js, OrganizationSearch/hooks/useOrganizations/useOrganizations.js, package.json
https://folio-org.atlassian.net/browse/UIPFO-51
https://github.com/folio-org/ui-plugin-find-organization/assets/88109087/13e02e21-64e3-4038-a128-517f0e4e7edd
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
=> UIPFO-51 Add additional filters to support reporting requirements

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
Update `upload-artifact` version
=> Update Github workflow actions

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UIPFO-59
https://folio-org.atlassian.net/browse/UIPFO-60
=> UIPFO-59 UIPFO-60 Migrate react-intl and stripes dependencies
